Repository conveyal/r5, pull requests merged in 2022-10, with the labels that each got.

#827 Path summaries: return raw data in JSON
  src/main/java/com/conveyal/r5/analyst/cluster/AnalysisWorker.java
  src/main/java/com/conveyal/r5/analyst/cluster/PathResult.java
  src/main/java/com/conveyal/r5/analyst/cluster/PathResultSummary.java
  src/main/java/com/conveyal/r5/transit/RouteInfo.java
  src/main/java/com/conveyal/r5/transit/TransitLayer.java
  src/main/java/com/conveyal/r5/transit/path/RouteSequence.java
  src/test/java/com/conveyal/r5/analyst/network/SimpsonDesertTests.java
Labels: feature, t0

#830 Remove vestiges of human-readable display
  src/test/java/com/conveyal/r5/analyst/network/SimpsonDesertTests.java
Labels: testing

#809 Add CodeQL Analysis Github Action
  .github/workflows/codeql-analysis.yml
  src/main/java/com/conveyal/r5/streets/StreetRouter.java
  src/main/java/com/conveyal/r5/transit/TransportNetworkCache.java
Labels: optimization
